/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGranolaStatusRouteImport } from './routes/api/granola.status'
import { Route as ApiGranolaSplatRouteImport } from './routes/api/granola.$'
import { Route as ApiAiCompletionsRouteImport } from './routes/api/ai.completions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGranolaStatusRoute = ApiGranolaStatusRouteImport.update({
  id: '/api/granola/status',
  path: '/api/granola/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGranolaSplatRoute = ApiGranolaSplatRouteImport.update({
  id: '/api/granola/$',
  path: '/api/granola/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCompletionsRoute = ApiAiCompletionsRouteImport.update({
  id: '/api/ai/completions',
  path: '/api/ai/completions',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/ai/completions': typeof ApiAiCompletionsRoute
  '/api/granola/$': typeof ApiGranolaSplatRoute
  '/api/granola/status': typeof ApiGranolaStatusRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/ai/completions': typeof ApiAiCompletionsRoute
  '/api/granola/$': typeof ApiGranolaSplatRoute
  '/api/granola/status': typeof ApiGranolaStatusRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/ai/completions': typeof ApiAiCompletionsRoute
  '/api/granola/$': typeof ApiGranolaSplatRoute
  '/api/granola/status': typeof ApiGranolaStatusRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/ai/completions'
    | '/api/granola/$'
    | '/api/granola/status'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/ai/completions' | '/api/granola/$' | '/api/granola/status'
  id:
    | '__root__'
    | '/'
    | '/api/ai/completions'
    | '/api/granola/$'
    | '/api/granola/status'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAiCompletionsRoute: typeof ApiAiCompletionsRoute
  ApiGranolaSplatRoute: typeof ApiGranolaSplatRoute
  ApiGranolaStatusRoute: typeof ApiGranolaStatusRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/granola/status': {
      id: '/api/granola/status'
      path: '/api/granola/status'
      fullPath: '/api/granola/status'
      preLoaderRoute: typeof ApiGranolaStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/granola/$': {
      id: '/api/granola/$'
      path: '/api/granola/$'
      fullPath: '/api/granola/$'
      preLoaderRoute: typeof ApiGranolaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/completions': {
      id: '/api/ai/completions'
      path: '/api/ai/completions'
      fullPath: '/api/ai/completions'
      preLoaderRoute: typeof ApiAiCompletionsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAiCompletionsRoute: ApiAiCompletionsRoute,
  ApiGranolaSplatRoute: ApiGranolaSplatRoute,
  ApiGranolaStatusRoute: ApiGranolaStatusRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
